import { useEffect, useState } from 'react';
import { api, QueueSummary } from '../lib/api';

export default function QueuesPage() {
  const [queues, setQueues] = useState<QueueSummary[]>([]);
  const [error, setError] = useState('');
  const load = () => api<{ queues: QueueSummary[] }>('/api/queues').then((value) => setQueues(value.queues)).catch((e) => setError(e.message));
  useEffect(() => { load(); const timer = setInterval(load, 5000); return () => clearInterval(timer); }, []);
  const retry = async (queue: string, id: string) => { try { await api(`/api/queues/${queue}/jobs/${id}/retry`, { method: 'POST' }); load(); } catch (e: any) { setError(e.message); } };
  return <><div className="page-header"><div><h2>Queue monitor</h2><p>Watch the content pipeline as jobs move from research to publishing.</p></div><button className="button secondary" onClick={load}>↻ Refresh</button></div>{error && <div className="notice warning">{error}</div>}<div className="grid three">{queues.map((queue) => { const active = Number(queue.counts?.active || 0); const waiting = Number(queue.counts?.waiting || 0); const failed = Number(queue.counts?.failed || 0); return <div className="card" key={queue.name}><div className="kicker">{queue.name.replace('viralforge-', '')}</div><div style={{ display: 'flex', gap: 17, marginTop: 16 }}><div><div className="stat-value" style={{ fontSize: 24 }}>{waiting}</div><small className="muted">waiting</small></div><div><div className="stat-value" style={{ fontSize: 24 }}>{active}</div><small className="muted">active</small></div><div><div className="stat-value" style={{ fontSize: 24, color: failed ? '#ae4e4e' : undefined }}>{failed}</div><small className="muted">failed</small></div></div><div className="queue-bar"><div style={{ width: `${Math.min(100, active * 20 + waiting * 5)}%` }} /></div></div> })}</div><div className="section-title"><h3>Failed jobs</h3></div><div className="card"><div className="table-wrap"><table className="table"><thead><tr><th>Queue</th><th>Job</th><th>Reason</th><th /></tr></thead><tbody>{queues.flatMap((queue) => (queue.jobs?.failed || []).map((job) => <tr key={`${queue.name}-${job.id}`}><td>{queue.name.replace('viralforge-', '')}</td><td className="mono">{job.id}</td><td>{job.failedReason || 'Unknown error'}</td><td><button className="button secondary" onClick={() => retry(queue.name, job.id)}>Retry</button></td></tr>))}{queues.every((queue) => !queue.jobs?.failed?.length) && <tr><td colSpan={4}><div className="empty">No failed jobs. Your pipeline is clear.</div></td></tr>}</tbody></table></div></div></>;
}
