import { useEffect, useState } from 'react';
import { api } from '../lib/api';

export default function SettingsPage() {
  const [settings, setSettings] = useState<any>(null);
  const [error, setError] = useState('');
  useEffect(() => { api<any>('/api/settings').then(setSettings).catch((e) => setError(e.message)); }, []);
  return <><div className="page-header"><div><h2>Settings & safety</h2><p>Operational readiness and controls for your content studio.</p></div></div>{error && <div className="notice warning">{error}</div>}<div className="card"><div className="notice warning"><strong>Publishing protection is active.</strong><br />PUBLISHING_DISABLED is currently true. Generation, rendering and validation can be tested safely; final Meta publishing is blocked.</div><div className="grid two"><div><div className="section-title" style={{ marginTop: 0 }}><h3>Services</h3></div>{settings && Object.entries(settings.services || {}).map(([name, service]: [string, any]) => <div className="service-row" key={name}><div><span style={{ textTransform: 'capitalize' }}>{name}</span>{name === 'omniroute' && service.ok && <div className="muted" style={{ fontSize: 11, marginTop: 4 }}>Model: {service.model} · {service.availableModels?.length || 0} models available</div>}{name === 'omniroute' && !service.ok && service.error && <div className="muted" style={{ fontSize: 11, marginTop: 4 }}>{service.error}</div>}</div><span className={`service-status ${service.ok ? 'ok' : 'off'}`}>● {service.ok ? 'Ready' : 'Needs attention'}</span></div>)}</div><div><div className="section-title" style={{ marginTop: 0 }}><h3>Runtime limits</h3></div><div className="service-row"><span>Posts per account/day</span><strong>{settings?.limits?.maxPostsPerDayPerAccount || '—'}</strong></div><div className="service-row"><span>Jobs per organization/hour</span><strong>{settings?.limits?.maxJobsPerHourPerOrg || '—'}</strong></div><div className="service-row"><span>Environment</span><strong>{settings?.environment || '—'}</strong></div></div></div></div></>;
}
